name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_first_job:
   name: my first job
    env:
      CI: true

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15.4.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install

      - name: Run UTs
        run: npm start

   my_second_job:
    needs: my_first_job

    env:
      CI: true

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15.4.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Open Client
        run: cd client

      - name: Install dependencies
        run: npm install

      - name: Run UTs
        run: npm start

    - name: Build production app
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build


    
